
name: .NET

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '9.0' # The .NET SDK version to use

jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore Rpbdis5/RadiostationWeb/RadiostationWeb/RadiostationWeb.csproj

      
    - name: Install dependencies for test project
      run: dotnet restore Rpbdis5/RadiostationWeb/Tests/Tests.csproj
      
    - name: Build
      run: dotnet build Rpbdis5/RadiostationWeb/RadiostationWeb/RadiostationWeb.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet test Rpbdis5/RadiostationWeb/Tests/Tests.csproj --no-restore --verbosity normal
